### ISSUE TITLE
What MIME type to use for MS Office 2013 attachments like docx, xlsx etc.

### ISSUE THREAD

**Issue by igororlov** [difi/vefa-portal#10]
Testing against Validator: https://vefa.difi.no/validator/

According to 
https://www.sitepoint.com/web-foundations/mime-types-summary-list/
https://stackoverflow.com/questions/4212861/what-is-a-correct-mime-type-for-docx-pptx-etc

it has to be 
application/vnd.openxmlformats-officedocument.wordprocessingml.document for docx
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet for xlsx
and application/vnd.openxmlformats-officedocument.presentationml.presentation for pptx

but we get an error message that these MIME types are illegal, while the old ones (for .doc and .xls) are supported: application/vnd.ms-excel and application/msword are in the list.

**Comment by klakegg** [comment]
This is related to specific specifications, not to any content versioned in this project.
