### ISSUE TITLE
EHF Validator

### ISSUE THREAD

**Issue by almiz** [difi/vefa-portal#2]
Hi, 

Getting a java error. if i remove some of the Detail lines im getting normal Validation Errors.

------------------------------------------------------------------------------------------------------------------

HTTP Status 500 - Request processing failed; nested exception is java.lang.StringIndexOutOfBoundsException: String index out of range: 10240

type Exception report

message Request processing failed; nested exception is java.lang.StringIndexOutOfBoundsException: String index out of range: 10240

description The server encountered an internal error that prevented it from fulfilling this request.

exception 
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.StringIndexOutOfBoundsException: String index out of range: 10240
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

root cause 
java.lang.StringIndexOutOfBoundsException: String index out of range: 10240
	java.lang.String.substring(String.java:1907)
	no.difi.vefa.validator.ValidationImpl.loadDocument(ValidationImpl.java:101)
	no.difi.vefa.validator.ValidationImpl.<init>(ValidationImpl.java:59)
	no.difi.vefa.validator.Validator.validate(Validator.java:83)
	no.difi.vefa.validator.service.ValidatorService.validateWorkspace(ValidatorService.java:77)
	no.difi.vefa.validator.controller.HomeController.upload(HomeController.java:44)
	sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

note The full stack trace of the root cause is available in the Apache Tomcat/7.0.52 (Ubuntu) logs.

Apache Tomcat/7.0.52 (Ubuntu)

**Comment by klakegg** [comment]
This is fixed and is not related to the content of this repository.
